### ISSUE TITLE
LUA error 'AbsorbMonitor'

### ISSUE THREAD

**Issue by jonomurphy** [Cortes-Jeremy/Gladius#10]
![WoWScrnShot_100921_220154](https://user-images.githubusercontent.com/13081559/136675728-217b60f6-2d1d-46e5-967c-9f69cca5b207.jpg)

**Comment by jonomurphy** [comment]
Pertains to gladius

**Comment by Cortes-Jeremy** [comment]
Hi, thank you for posting this error, I have some time to play this month, I fixed the error, just download new release.
